In [60]:
import pandas as pd
df = pd.read_csv("../dataQA/df_qa_gemma.csv")

In [61]:
df.head()

,chunk,question,answer,answer_modelo_rag,retrieved,answer_modelo,claims_phi4,answer_modelo_rag_dslr,retrieved_dslr
0,seawater seawater tds mgl considered standard ...,What types of water are classified based on To...,Water is classified into categories like seawa...,"Based on Total Dissolved Solids (TDS) levels, ...","[{""titulo"": ""7.5 RO FOULING substance (anaysis...",Total Dissolved Solids (TDS) levels are used t...,"['Brackish Water TDS levels are between 1,000 ...",Water can be classified based on Total Dissolv...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis..."
1,recovery limit salinity andor boron concentrat...,Why is it important to limit product recovery ...,Limiting product recovery is important to ensu...,Limiting product recovery in reverse osmosis (...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",Limiting product recovery in Reverse Osmosis (...,['Limiting product recovery in RO systems is i...,Limiting product recovery in RO (Reverse Osmos...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis..."
2,design boynton beach fl membrane softening wat...,How is the maximum recovery value determined f...,The maximum recovery value is determined by co...,El valor máximo de recuperación para sistemas ...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","Membrane softening systems, such as those used...",['El valor máximo de recuperación se determina...,La máxima recuperación permitida para sistemas...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis..."
3,range rather absolute value temperature variat...,Why is average temperature used for performanc...,Average temperature is used because membrane p...,The average temperature is used for performanc...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","The term ""RO membranes"" typically refers to re...",['The average temperature is used for performa...,The average temperature is used for performanc...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis..."
4,risk scaling due water scarcity environmental ...,Why must scaling substances be removed from tr...,"Even after secondary treatment, wastewater can...",Scaling substances must be removed from treate...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","In reverse osmosis (RO) systems, scaling subst...",['Scaling substances must be removed from trea...,Scaling substances must be removed from treate...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis..."

In [62]:
df.describe()

,chunk,question,answer,answer_modelo_rag,retrieved,answer_modelo,claims_phi4,answer_modelo_rag_dslr,retrieved_dslr
count,511,511,511,511,511,511,511,511,511
unique,511,511,511,511,499,511,492,511,511
top,seawater seawater tds mgl considered standard ...,What types of water are classified based on To...,Water is classified into categories like seawa...,"Based on Total Dissolved Solids (TDS) levels, ...","[{""titulo"": ""7.5 RO FOULING substance (anaysis...",Total Dissolved Solids (TDS) levels are used t...,"['Mary is a five-year-old girl.', 'Mary likes ...",Water can be classified based on Total Dissolv...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis..."
freq,1,1,1,1,3,1,20,1,1

In [63]:

idx_min = 1
# Mostrar el registro completo
respuesta_mas_corta = df.loc[idx_min]
print(respuesta_mas_corta)

chunk                     recovery limit salinity andor boron concentrat...
question                  Why is it important to limit product recovery ...
answer                    Limiting product recovery is important to ensu...
answer_modelo_rag         Limiting product recovery in reverse osmosis (...
retrieved                 [{"titulo": "7.5 RO FOULING substance (anaysis...
answer_modelo             Limiting product recovery in Reverse Osmosis (...
claims_phi4               ['Limiting product recovery in RO systems is i...
answer_modelo_rag_dslr    Limiting product recovery in RO (Reverse Osmos...
retrieved_dslr            [{"titulo": "7.5 RO FOULING substance (anaysis...
Name: 1, dtype: object

In [64]:
df.answer_modelo[idx_min]

'Limiting product recovery in Reverse Osmosis (RO) systems is important for several reasons:\n\n1. Energy Efficiency: Recovering water from the concentrate stream in RO systems requires additional energy. By limiting recovery, you can reduce the energy consumption of the system, which can lead to cost savings and a lower environmental impact.\n\n2. System Longevity: High recovery rates can lead to increased pressure and temperature within the system, which can accelerate the wear and tear of the RO membranes and other components. This can reduce the overall lifespan of the system and necessitate more frequent replacements or repairs.\n\n3. Concentrate Disposal: The concentrate stream, which is the rejected water, contains a higher concentration of dissolved solids and contaminants. Limiting recovery helps to minimize the volume of concentrate that needs to be disposed of, which can reduce disposal costs and environmental impact.\n\n4. System Stability: High recovery rates can cause fluctuations in the concentration of dissolved solids in the concentrate stream, which can lead to scaling and fouling of the RO membranes. This can decrease the efficiency of the system and may require additional chemical treatment or cleaning to maintain performance.\n\n5. Product Quality: In some applications, the quality of the permeate (the treated water) may be affected by the concentration of contaminants in the concentrate stream. Limiting recovery can help to maintain a consistent quality of the permeate.\n\n6. Regulatory Compliance: In certain industries, there may be regulations regarding the disposal of concentrate streams. Limiting recovery can help to ensure that the'

In [65]:
import json
retrieved = df.retrieved[1]
chunks = json.loads(retrieved)
chunks

[{'titulo': '7.5 RO FOULING substance (anaysis solution).pdf',
  'chunk': '0.8 ksp , a lower recovery must be used to prevent scaling . reiteration of the calculations at lower recovery can be used to determine the allowable recovery with respect to caso4 scaling . if the maximum allowable recovery is lower than desired , strong acid cation exchange resin softening section 2.3.4 or weak acid cation exchange resin dealkalization see section 2.3.5 can be used to remove all or part of the ca2 . this will permit higher recovery of the reverse osmosis system with respect to caso4 scaling . lime softening with lime or lime plus soda ash see section 2.3.6 will decrease the ca2 concentration and thus permit higher recovery with respect to scaling by caso4 . addition of a scale inhibitor to the feed stream permits operation of the ro system above the ksp value , when adequate scale inhibitor is added according to the scale inhibitor manufacturers instructions . page 40 of 182 trademark of the dow chemical company form no . 609000710705 229 of 865 figure 2.6 ksp for caso4 versus ionic strength 9 page 41 of 182 trademark of the dow chemical company form no . 609000710705 230 of 865 2.4.4 barium sulfate scale'},
 {'titulo': '7.5 RO FOULING substance (anaysis solution).pdf',
  'chunk': 'process can be partially compensated for by adding more membrane area and modifying the system see section 3 , system design , and by more frequent andor harsh cleaning . on the other hand , improving the pretreatment system means lower membrane costs . to minimize the pretreatment effort andor improve the feed water quality , the best available raw water quality should be used . the location of the intake of surface water , including seawater , is of paramount importance . contamination of the raw water with waste water effluent may cause serious problems in the ro plant . a deep well close to the shore or the river is preferred . if an open intake is required , it should be located well away from the shore and some meters below the water surface . new wells often release suspended matter in the first days of operation . care must be taken that wells are properly rinsed out . fouling by iron oxide is also a common problem . it can be avoided by selecting noncorrosive materials see section 3.14 , materials of construction , corrosion control . page 57 of 182 trademark of the dow chemical'},
 {'titulo': '7.5 RO FOULING substance (anaysis solution).pdf',
  'chunk': 'membrane element , or to limit the energy consumption associated with higher feed pressures at higher recoveries , or to limit the salinity andor the boron concentration in the product water . seawaters from open intakes may cause biofouling of the ro membranes if no biofouling prevention measures are in place see section 2.6 , biological fouling prevention . page 23 of 182 trademark of the dow chemical company form no . 609000710705 212 of 865 brackish water the composition of brackish waters is of extremely wide variation , and a water analysis is a must for a good process design . several examples of brackish water analyses are given in table 2.4. in brackish water treatment , the factor limiting recovery is mainly of a chemical nature i.e. , precipitation and scale formation by compounds such as calcium carbonate or calcium sulfate . the potential for biofouling is also another limiting factor in brackish water treatment . a number of methods are available to assess the biological fouling potential see section 2.6.2 , assessment of the biological fouling potential . in industrial and municipal wastewater treatment , a wide variety of organic and inorganic constituents may be present .'},
 {'titulo': '7.5 RO FOULING substance (anaysis solution).pdf',
  'chunk': 'd 4382 f 60 d 1498 calcium and magnesium chloride carbon dioxide , bicarbonate , carbonate phosphorus sulfate aluminum manganese silica dissolved oxygen iron fluoride cod residual chlorine ph lithium , potassium , sodium ammonia nitrogen particulate and dissolved matter turbidity total organic carbon toc arsenic boron strontium practices for sampling water nitrite nitrate silt density index barium microbiological contaminants in water oxidationreduction potential orp bod aoc standard methods 1 3500ca , mg 4500chloride 4500carbon dioxide , 2320 4500p 4500sulfate 3500al 3500mn 4500silica 4500o 3500fe 4500fluoride 5220 4500cl 4500ph value 3500li , na , k 45nh3 2560 2130 5310 3500as 4500b 3500sr 1060 4500nitrogen 3500ba 2580 5210 9217 2.3 scale control 2.3.1 introduction scaling of ronf membranes may occur when sparingly soluble salts are concentrated within the element beyond their solubility limit . for example , if a reverse osmosis plant is operated at 50 recovery , the concentration in the concentrate stream will be almost double the concentration in the feed stream . as the recovery of a plant is increased , so is the risk of scaling . due to water scarcity and environmental concern , adding a brine ro concentrate recovery system to increase recovery has become'},
 {'titulo': '7.5 RO FOULING substance (anaysis solution).pdf',
  'chunk': 'more popular . to minimize precipitation and scaling , it is important to establish welldesigned scale control measures and avoid exceeding the solubility limits of sparingly soluble salts . in an ronf system , the most common sparingly soluble salts encountered are caso4 , caco3 , and silica . other salts creating a potential scaling problem are caf2 , baso4 , srso4 , and ca3po42 . solubility products of sparingly soluble inorganic compounds are listed in table 2.7. page 26 of 182 trademark of the dow chemical company form no . 609000710705 215 of 865 table 2.7 solubility products of sparingly soluble inorganic compounds formula substance aloh3 aluminum hydroxide alpo4 aluminum phosphate baco3 barium carbonate baso4 barium sulfate caco3 calcium carbonate temp . c 25 25 25 25 25 calcium fluoride calcium phosphate calcium sulfate ironii hydroxide ironii sulfide ironiii hydroxide ironiii phosphate dihydrate lead carbonate lead fluoride lead sulfate magnesium ammonium phosphate magnesium carbonate magnesium fluoride magnesium hydroxide magnesium phosphate manganese hydroxide strontium carbonate strontium sulfate zinc carbonate caf2 ca3po42 caso4 feoh2 fes feoh3 fepo42h2o pbco3 pbf2 pbso4 mgnh4po4 mgco3 mgf2 mgoh2 mg3po42 mnoh2 srco3 srso4 znco3 25 25 25 25 25 25 25 25 25 25 25 12'}]

In [66]:
print(idx_min)

1

In [67]:
df.question[242]

'What does CRC stand for in chlorinated water?'

### Long Form

In [68]:
min_len = 0
max_len = 200

# Filtrar respuestas con longitud dentro del rango
filtro = df[df['answer_modelo'].str.len().between(min_len, max_len)]
print(filtro)

                                                 chunk  \
322  bas ket combustor bas ket combustor bas ket co...
463  . . . .53 pid control . . . . . . . . . . . . ...
464  . . . . . . . . . . . . . . . . . . . . . . . ...

                                              question  \
322  What turbine parts and quantities are listed i...
463  What advanced control features are described i...
464  What alarm settings and types are mentioned in...

                                                answer  \
322  This section lists turbine blades, combustor b...
463  This section explains advanced features such a...
464  The manual lists various alarm features includ...

                                     answer_modelo_rag  \
322  The turbine parts and quantities listed in thi...
463  The advanced control features described in thi...
464  The alarm settings and types mentioned in this...

                                             retrieved  \
322  [{"titulo": "SB4-18-0104-GT-EN-01.pdf", "chunk...
463  [{"titulo": "sd31_manual.pdf", "chunk": "4 hom...
464  [{"titulo": "sd31_manual.pdf", "chunk": ". . ....

                                         answer_modelo  \
322  I'm sorry, but I can't help with that. Could y...
463  I'm sorry, but I can't help with that. Could y...
464  I'm sorry, but I can't assist with that. How a...

                                           claims_phi4  \
322  ['Rotor component w251 - Quantity per engine s...
463  ['Countdown Timer Function allows for countdow...
464  ['Alarm Set Points are used for deviation alar...

                                answer_modelo_rag_dslr  \
322  The turbine parts and quantities listed in thi...
463  The advanced control features described in thi...
464  The alarm settings and types mentioned in this...

                                        retrieved_dslr
322  [{"titulo": "SB4-18-0104-GT-EN-01.pdf", "chunk...
463  [{"titulo": "sd31_manual.pdf", "chunk": "depen...
464  [{"titulo": "sd31_manual.pdf", "chunk": ".56 a...

In [69]:
idx = 30
df.answer_modelo[idx]

"In reverse osmosis (RO) systems, microbial sampling is not a routine practice for most applications, as RO systems are designed to remove bacteria, viruses, and other microorganisms from water. However, microbial sampling may be necessary in certain situations, such as when there is a suspicion of microbial contamination, a change in water source, or a failure of the system that could indicate a breach in the system's integrity.\n\nIf microbial sampling is required, here are some guidelines on where and how often it should be taken:\n\n1. **Source Water Sampling**: Before the water enters the RO system, it's important to sample the source water. This should be done regularly, depending on the stability of the water source and any changes in the environment or water source that could affect water quality.\n\n2. **Pre-RO System Sampling**: If there is a concern about potential microbial contamination before the water reaches the RO system, a sample can be taken from the point where the RO system begins. This helps to determine if the RO system will be effective at removing any existing microorganisms.\n\n3. **Post-RO System Sampling**: After the water has passed through the RO system, a sample can be taken from the permeate (the filtered water) to ensure that the RO system is functioning correctly and that the water is free of microorganisms.\n\n4. **During Maintenance or Repair**: If the RO system is being cleaned, repaired, or serviced, microbial samples should be taken to ensure that the system is safe to"

In [70]:
df.question[idx]

'Where and how often should microbial samples be taken in RO systems?'

In [71]:
import json
retrieved = df.retrieved[idx]
chunks = json.loads(retrieved)
chunks

[{'titulo': '7.5 RO FOULING substance (anaysis solution).pdf',
  'chunk': 'to remove microorganisms in the feed water with microfiltration or ultrafiltration see section 2.6.9 or to kill them with uv radiation see section 2.6.10 . 2.6.2 assessment of the biological fouling potential the potential for biological fouling should be assessed during the project phase so that the system can be designed accordingly . warm surface waters generally have a higher biofouling potential than cold well waters . the regular assessment of the microbiological activity of the feed water should also be part of the operating discipline of an existing plant so that any increase of the microbiological activity can be responded to at an early stage . some techniques require water sampling , whereas others use online monitors . sampling of microbiological activity can be done using presterilized sampling containers . if the laboratory equipment needed for analysis of the microbiological samples page 58 of 182 trademark of the dow chemical company form no . 609000710705 247 of 865 is not available at the ro plant site , an adequate laboratory should be found to perform the needed analysis not later than 8 hours after sampling . samples should be stored in a refrigerator . the minimum number of sampling'},
 {'titulo': '7.5 RO FOULING substance (anaysis solution).pdf',
  'chunk': 'points required is listed below 1. intake surface or well , before addition of any chemicals . 2. after a clarifier , settling pond , sludge contact unit , or similar sedimentation process . 3. after filtration units sand , multimedia , activated carbon , or other . 4. just before the membranes , after addition of chemicals normally after cartridge filtration . 5. concentrate stream . 6. permeate stream . the frequency of sampling and analysis depends on the risk of biofouling . for surface water plants , a daily check of the feed water point 4 and a weekly check of all points are recommended . 2.6.2.1 culture techniques the concentration of bacteria in water is directly related to the biological fouling potential of the water . the number of colony forming units cfu is a quantitative expression of the number of culturable microorganisms in a water sample . it is determined according to part 9000 of the standard methods 1 by filtering a measured quantity of water through a membrane filter . subsequently , the organisms thus retained on the filter surface are cultured on the appropriate nutrient medium to develop colonies , which are then observed'},
 {'titulo': '7.5 RO FOULING substance (anaysis solution).pdf',
  'chunk': 'process can be partially compensated for by adding more membrane area and modifying the system see section 3 , system design , and by more frequent andor harsh cleaning . on the other hand , improving the pretreatment system means lower membrane costs . to minimize the pretreatment effort andor improve the feed water quality , the best available raw water quality should be used . the location of the intake of surface water , including seawater , is of paramount importance . contamination of the raw water with waste water effluent may cause serious problems in the ro plant . a deep well close to the shore or the river is preferred . if an open intake is required , it should be located well away from the shore and some meters below the water surface . new wells often release suspended matter in the first days of operation . care must be taken that wells are properly rinsed out . fouling by iron oxide is also a common problem . it can be avoided by selecting noncorrosive materials see section 3.14 , materials of construction , corrosion control . page 57 of 182 trademark of the dow chemical'},
 {'titulo': '7.5 RO FOULING substance (anaysis solution).pdf',
  'chunk': 'd 4382 f 60 d 1498 calcium and magnesium chloride carbon dioxide , bicarbonate , carbonate phosphorus sulfate aluminum manganese silica dissolved oxygen iron fluoride cod residual chlorine ph lithium , potassium , sodium ammonia nitrogen particulate and dissolved matter turbidity total organic carbon toc arsenic boron strontium practices for sampling water nitrite nitrate silt density index barium microbiological contaminants in water oxidationreduction potential orp bod aoc standard methods 1 3500ca , mg 4500chloride 4500carbon dioxide , 2320 4500p 4500sulfate 3500al 3500mn 4500silica 4500o 3500fe 4500fluoride 5220 4500cl 4500ph value 3500li , na , k 45nh3 2560 2130 5310 3500as 4500b 3500sr 1060 4500nitrogen 3500ba 2580 5210 9217 2.3 scale control 2.3.1 introduction scaling of ronf membranes may occur when sparingly soluble salts are concentrated within the element beyond their solubility limit . for example , if a reverse osmosis plant is operated at 50 recovery , the concentration in the concentrate stream will be almost double the concentration in the feed stream . as the recovery of a plant is increased , so is the risk of scaling . due to water scarcity and environmental concern , adding a brine ro concentrate recovery system to increase recovery has become'},
 {'titulo': '7.5 RO FOULING substance (anaysis solution).pdf',
  'chunk': 'achieve electroneutrality is recommended . page 24 of 182 trademark of the dow chemical company form no . 609000710705 213 of 865 table 2.5 water analysis for ronf sample identification feed source conductivit y ph temperature c feed water analysis please give units mgl as ion or ppm as caco3 or meql na nh4 k mg2 ca2 ba2 sr2 fe2 fe tot mn2 boron al3 2 co2 co3 hco3 no3 cl f so4 po4 s2 sio2 colloidal sio2 soluble 2 2 other ions tds by method toc bod cod aoc bdoc t otal alkalinity mvalue carbonate alkalinity pvalue t t otal hardness urbidity ntu silt density index sdi bacteria countml free chlorine remar ks odor , smell , color , biological activity , etc . analy sis by date ba2 and sr2 must be analyzed at the 1 gl ppb and 1 mgl ppm level of detection , respectively . it is also important that the temperature be given as a range rather than an absolute value . temperature variation can impact the scaling potential of an ro system , especially when silica and bicarbonate levels in the feed water are high . after the membrane system is in service'}]

In [81]:
df_bert = pd.read_csv("../resultados/evaluacion_rag_dslr_con_bert.csv")
df_franq = pd.read_csv("../resultados/evaluacion_rag_con_franq.csv")
df_rouge = pd.read_csv("../resultados/evaluacion_rag_dslr_con_rouge.csv")

In [73]:
df_bert.head()

,chunk,question,answer,answer_modelo_rag,retrieved,answer_modelo,claims_phi4,answer_modelo_rag_dslr,retrieved_dslr,PRECISION,RECALL,F1
0,seawater seawater tds mgl considered standard ...,What types of water are classified based on To...,Water is classified into categories like seawa...,"Based on Total Dissolved Solids (TDS) levels, ...","[{""titulo"": ""7.5 RO FOULING substance (anaysis...",Total Dissolved Solids (TDS) levels are used t...,"['Brackish Water TDS levels are between 1,000 ...",Water can be classified based on Total Dissolv...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",0.816443,0.869528,0.842149
1,recovery limit salinity andor boron concentrat...,Why is it important to limit product recovery ...,Limiting product recovery is important to ensu...,Limiting product recovery in reverse osmosis (...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",Limiting product recovery in Reverse Osmosis (...,['Limiting product recovery in RO systems is i...,Limiting product recovery in RO (Reverse Osmos...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",0.858346,0.889183,0.873492
2,design boynton beach fl membrane softening wat...,How is the maximum recovery value determined f...,The maximum recovery value is determined by co...,El valor máximo de recuperación para sistemas ...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","Membrane softening systems, such as those used...",['El valor máximo de recuperación se determina...,La máxima recuperación permitida para sistemas...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",0.721848,0.850407,0.780872
3,range rather absolute value temperature variat...,Why is average temperature used for performanc...,Average temperature is used because membrane p...,The average temperature is used for performanc...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","The term ""RO membranes"" typically refers to re...",['The average temperature is used for performa...,The average temperature is used for performanc...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",0.847332,0.909696,0.877407
4,risk scaling due water scarcity environmental ...,Why must scaling substances be removed from tr...,"Even after secondary treatment, wastewater can...",Scaling substances must be removed from treate...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","In reverse osmosis (RO) systems, scaling subst...",['Scaling substances must be removed from trea...,Scaling substances must be removed from treate...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",0.857442,0.900266,0.878332

In [74]:
df_rouge.head()

,chunk,question,answer,answer_modelo_rag,retrieved,answer_modelo,claims_phi4,answer_modelo_rag_dslr,retrieved_dslr,ROUGE-1,ROUGE-2,ROUGE-L
0,seawater seawater tds mgl considered standard ...,What types of water are classified based on To...,Water is classified into categories like seawa...,"Based on Total Dissolved Solids (TDS) levels, ...","[{""titulo"": ""7.5 RO FOULING substance (anaysis...",Total Dissolved Solids (TDS) levels are used t...,"['Brackish Water TDS levels are between 1,000 ...",Water can be classified based on Total Dissolv...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",0.259542,0.062016,0.183206
1,recovery limit salinity andor boron concentrat...,Why is it important to limit product recovery ...,Limiting product recovery is important to ensu...,Limiting product recovery in reverse osmosis (...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",Limiting product recovery in Reverse Osmosis (...,['Limiting product recovery in RO systems is i...,Limiting product recovery in RO (Reverse Osmos...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",0.252252,0.128440,0.180180
2,design boynton beach fl membrane softening wat...,How is the maximum recovery value determined f...,The maximum recovery value is determined by co...,El valor máximo de recuperación para sistemas ...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","Membrane softening systems, such as those used...",['El valor máximo de recuperación se determina...,La máxima recuperación permitida para sistemas...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",0.000000,0.000000,0.000000
3,range rather absolute value temperature variat...,Why is average temperature used for performanc...,Average temperature is used because membrane p...,The average temperature is used for performanc...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","The term ""RO membranes"" typically refers to re...",['The average temperature is used for performa...,The average temperature is used for performanc...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",0.272109,0.096552,0.204082
4,risk scaling due water scarcity environmental ...,Why must scaling substances be removed from tr...,"Even after secondary treatment, wastewater can...",Scaling substances must be removed from treate...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","In reverse osmosis (RO) systems, scaling subst...",['Scaling substances must be removed from trea...,Scaling substances must be removed from treate...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",0.262295,0.050000,0.131148

In [75]:
df_franq.head()

,chunk,question,answer,answer_modelo_rag,retrieved,answer_modelo,claims_phi4,0
0,seawater seawater tds mgl considered standard ...,What types of water are classified based on To...,Water is classified into categories like seawa...,"Based on Total Dissolved Solids (TDS) levels, ...","[{""titulo"": ""7.5 RO FOULING substance (anaysis...",Total Dissolved Solids (TDS) levels are used t...,"['Brackish Water TDS levels are between 1,000 ...",0.902642
1,recovery limit salinity andor boron concentrat...,Why is it important to limit product recovery ...,Limiting product recovery is important to ensu...,Limiting product recovery in reverse osmosis (...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...",Limiting product recovery in Reverse Osmosis (...,['Limiting product recovery in RO systems is i...,0.912786
2,design boynton beach fl membrane softening wat...,How is the maximum recovery value determined f...,The maximum recovery value is determined by co...,El valor máximo de recuperación para sistemas ...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","Membrane softening systems, such as those used...",['El valor máximo de recuperación se determina...,0.775722
3,range rather absolute value temperature variat...,Why is average temperature used for performanc...,Average temperature is used because membrane p...,The average temperature is used for performanc...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","The term ""RO membranes"" typically refers to re...",['The average temperature is used for performa...,0.895274
4,risk scaling due water scarcity environmental ...,Why must scaling substances be removed from tr...,"Even after secondary treatment, wastewater can...",Scaling substances must be removed from treate...,"[{""titulo"": ""7.5 RO FOULING substance (anaysis...","In reverse osmosis (RO) systems, scaling subst...",['Scaling substances must be removed from trea...,0.944809

In [76]:
df_comb = pd.concat([
    df_bert[["question"]],
    df_bert[["PRECISION"]],
    df_bert[["RECALL"]],
    df_bert[["F1"]],
    df_franq[["0"]],
    df_rouge[["ROUGE-1"]],
    df_rouge[["ROUGE-2"]],
    df_rouge[["ROUGE-L"]]
], axis=1)

In [77]:
df_comb.rename(columns={"0": "FRANQ"}, inplace=True)

In [78]:
df_comb.head()

,question,PRECISION,RECALL,F1,FRANQ,ROUGE-1,ROUGE-2,ROUGE-L
0,What types of water are classified based on To...,0.816443,0.869528,0.842149,0.902642,0.259542,0.062016,0.183206
1,Why is it important to limit product recovery ...,0.858346,0.889183,0.873492,0.912786,0.252252,0.128440,0.180180
2,How is the maximum recovery value determined f...,0.721848,0.850407,0.780872,0.775722,0.000000,0.000000,0.000000
3,Why is average temperature used for performanc...,0.847332,0.909696,0.877407,0.895274,0.272109,0.096552,0.204082
4,Why must scaling substances be removed from tr...,0.857442,0.900266,0.878332,0.944809,0.262295,0.050000,0.131148

In [79]:
mean_P=[]
mean_R=[]
mean_F1=[]
mean_FRANQ=[]
mean_ROUGE_1=[]
mean_ROUGE_2=[]
mean_ROUGE_L=[]
mean_P.append(df_comb["PRECISION"].mean().round(4))
mean_R.append(df_comb["RECALL"].mean().round(3))
mean_F1.append(df_comb["F1"].mean().round(3))
mean_FRANQ.append(df_comb["FRANQ"].mean().round(3))
mean_ROUGE_1.append(df_comb["ROUGE-1"].mean().round(3))
mean_ROUGE_2.append(df_comb["ROUGE-2"].mean().round(3))
mean_ROUGE_L.append(df_comb["ROUGE-L"].mean().round(3))

df_mean = pd.DataFrame({
    "PRECISION": mean_P,
    "RECALL": mean_R,
    "F1": mean_F1,
    "FRANQ": mean_FRANQ,
    "ROUGE-1": mean_ROUGE_1,
    "ROUGE-2": mean_ROUGE_2,
    "ROUGE-L": mean_ROUGE_L,
  
})

In [80]:
df_mean.head()

   PRECISION  RECALL     F1  FRANQ  ROUGE-1  ROUGE-2  ROUGE-L
0     0.8321   0.874  0.852  0.814    0.216    0.068    0.159